### PR TITLE
Regex error

### PR DESCRIPTION
**Pull request by k2w2yut**
I tried to use the component and found an error at this line.
Fixing the regex pattern help build complete but please verify the function validity

### CODE REVIEW

**Comment by danielcondemarin** [comment]
@k2w2yut Can you expand on which error you found? 

The regex seems to be work fine as is. The job of the regex is to convert next bracketed dynamic routes to express ones (using `:`). 

For example:

image

With your change it breaks:

image

**Comment by k2w2yut** [comment]
image

It just simply syntax error when I try to deploy the code.
Disclaimer: I'm not a front-end dev, only taking care of bringing project up to AWS environment.

**Comment by danielcondemarin** [comment]
@k2w2yut You will need at least node 10.x.x for this to work. Otherwise it might be available in earlier versions by using `--harmony-regexp-named-captures`. See https://github.com/nodejs/node/issues/19760

**Comment by k2w2yut** [comment]
I see thank you to point that out

> @k2w2yut You will need at least node 10.x.x for this to work. Otherwise it might be available in earlier versions by using `--harmony-regexp-named-captures`. See [nodejs/node#19760](https://github.com/nodejs/node/issues/19760)

I see, thank you for point that out

**Pull request closed without merging**
