### PR TITLE
S3 upload fix

### PR DESCRIPTION
**Pull request by jlaramie**
Fix for #386 

@danielcondemarin I couldn't get my local instance to use the mono repo properly so I wasn't able to test this fix. I"ll need to look into or get help with how to develop with the new tooling.

### CODE REVIEW

**Comment by danielcondemarin** [comment]
> Fix for #386
> 
> @danielcondemarin I couldn't get my local instance to use the mono repo properly so I wasn't able to test this fix. I"ll need to look into or get help with how to develop with the new tooling.

I need to update the Contributing guide with a proper guide. In the meantime you should get it up and running the monorepo by doing:

```
cd /path/to/your_fork/serverless-next.js

npm install
npm run packages-install
npm run test
```

To test and deploy your changes locally, you can point an example app to your fork:

```
# your serverless.yml
nextApp:
  component: "/path/to/your/fork/serverless-next.js/packages/serverless-component"
  inputs:
    ...
```

**Comment by stan-sack** [comment]
> > Fix for #386
> > @danielcondemarin I couldn't get my local instance to use the mono repo properly so I wasn't able to test this fix. I"ll need to look into or get help with how to develop with the new tooling.
> 
> I need to update the Contributing guide with up to date info. In the meantime you should get it up and running the monorepo by doing:
> 
> ```
> cd /path/to/your_fork/serverless-next.js
> 
> npm install
> npm run packages-install
> npm run test
> ```
> 
> To test and deploy your changes locally, you can point an example app to your fork:
> 
> ```
> # your serverless.yml
> nextApp:
>   component: "/path/to/your/fork/serverless-next.js/packages/serverless-component"
>   inputs:
>     ...
> ```
> 
> Since you are working with `s3-static-assets` you will need to rebuild it `npm run build` before deploying.

I had issues with this as well. great to see its an easy fix

**Comment by jlaramie** [comment]
@danielcondemarin I added two tests to check this feature. 

The first is within serverless-component to ensure that the configuration can be passed through.

The second test is inside s3-static-assets to ensure it takes the config parameter and uses it

**Comment by jlaramie** [comment]
Well it looks like you like the changes at least :)

**Comment by jlaramie** [comment]
Those tests took me a while to figure out what to do, but I eventually put something together

**Comment by danielcondemarin** [comment]
> Those tests took me a while to figure out what to do, but I eventually put something together

What did you think of the testing approach in general? I'd appreciate any feedback you have. 

I'm keen on having a good testing approach so is easier for contributors to add features and test them as well.

**Comment by jlaramie** [comment]
> Let me know if you're happy with the PR as it currently stands and I'll get it merged and published 🚀

@danielcondemarin Looks good to me!

> What did you think of the testing approach in general? I'd appreciate any feedback you have.

I'll be honest, this is the most I've used Jest Mocks in a long time. It has been a great refresher. The parts I've looked at make a lot of sense. Having TS types for the tests also helps a lot.

**Comment by danielcondemarin** [comment]
> > Let me know if you're happy with the PR as it currently stands and I'll get it merged and published 🚀
> 
> @danielcondemarin Looks good to me!
> 
> > What did you think of the testing approach in general? I'd appreciate any feedback you have.
> 
> I'll be honest, this is the most I've used Jest Mocks in a long time. It has been a great refresher. The parts I've looked at make a lot of sense. Having TS types for the tests also helps a lot.

Awesome I'll publish in a few mins. 

I'm slowly migrating the whole project to TS, makes such a good difference. Much easier code navigation, especially for new starters to the project.

**Comment by danielcondemarin** [comment]
Just published `serverless-next.js@1.11.4` 🎉

**Pull request merged**
