### PR TITLE
useNakedDomain option added

### LINKED ISSUE #192: Redirect non-www to www and vice-versa
Add an option to enable redirect from `example.com` to `www.example.com` and vice-versa.
For example, add option `redirect` to force redirect to www:

```
myApp:
  component: serverless-next.js
  inputs:
    domain: ["www", "example.com"]
    redirect: true
```

### PR DESCRIPTION
**Pull request by endigo**
This time it definitely works as I expected.

Ref #293 

Close #192

### CODE REVIEW

**Comment by barrysteyn** [comment]
The domain component has this feature already built in?

**Comment by endigo** [comment]
@barrysteyn But serverless-next.js component doesn't expose that feature.

**Comment by endigo** [comment]
@danielcondemarin Hey, please review this PR.

**Comment by SarKurd** [comment]
@danielcondemarin could you confirm if we still need this? we are about to deploy a V2 of our app to a naked domain which uses this plugin, we don't have a way to test if it works as we don't have a spare domain to test on it as the V1 of our app uses it.

**Comment by owlas** [comment]
Hey @endigo thanks for adding this. What exactly would I use in my config to have naked domain AND www subdomain point to my application?

**Comment by owlas** [comment]
Actually this already works for me:
```yaml
myWhackyApp:
  component: serverless-next.js
  inputs:
    domain: "mydomain.com"
```

**Comment by endigo** [comment]
@owlas It creates an only naked domain. Then you can redirect `www` to the naked one.

**Comment by owboateng** [comment]
Sorry but can someone please show how to use the naked domain option. Currently I get two aliases created in Route53 for www and non www with both pointing to cloudfront. This causes them to be seen as two different sites which is affecting my SEO

**Comment by endigo** [comment]
@owboateng Unfortunately, this PR is not merged yet.

You can create custom Cloudfront distribution which redirects to the other one.

When you deploy your web to AWS using serverless command it will fail because of a duplicated record of Cloudfront, but it'll work fine.

I tried to solve this issue with this PR.

Thanks

**Comment by owboateng** [comment]
@endigo Thanks for the quick response. Any one here knows when this PR will be integrated? Thanks

**Comment by lone-cloud** [comment]
do you mind adding a test and fixing the conflicts. I'll test this out after.

**Comment by lone-cloud** [comment]
I'd like to handle this differently. Closing but I'll be addressing it in #465

**Pull request closed without merging**
